### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/stock-logistics-workflow#167]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] mrp_lock_lot
- [ ] picking_dispatch > stock_batch_picking - Assigned to @cyrilgdn - #241 
- [ ] picking_dispatch_wave
- [ ] product_customer_code_picking
- [ ] product_serial
- [ ] stock_cancel
- [x] stock_disable_force_availability_button - By @nicomacr - #278 
- [ ] stock_dropshipping_dual_invoice
- [x] ~~stock_filter_none_zero_qty~~ - Not needed since quants
- [ ] stock_inventory_retry_assign
- [ ] stock_location_flow_creator
- [ ] stock_lock_lot
- [x] stock_lot_scrap - By @pedrobaeza - #280 
- [ ] stock_move_backdating
- [ ] stock_move_description
- [ ] stock_move_on_hold
- [ ] stock_obsolete
- [ ] stock_ownership_availability_rules
- [ ] stock_ownership_by_move
- [ ] stock_picking_backorder_strategy
- [x] stock_picking_back2draft - By @nicomacr - #276 
- [ ] stock_picking_compute_delivery_date
- [ ] stock_picking_deliver_uos
- [x] stock_picking_invoice_link - By @flotho merged in one module in OCA/account-invoicing/pull/140 - Alt. migration of only this module: #261
- [x] stock_picking_mass_assign - By @mdietrichc2c - #244
- [ ] stock_picking_package_preparation - #199
- [ ] stock_picking_package_preparation_line - #199
- [ ] stock_picking_priority
- [x] stock_picking_reorder_lines > stock_picking_line_sequence - By @mreficent - #385 
- [ ] stock_picking_show_return - By @pedrobaeza - #251 
- [ ] stock_sale_filters
- [x] stock_split_picking ~~@yvaucher #201~~ - By @lmignon #381 
- [ ] stock_transfer_split_multi
- [ ] stock_route_sales_team

**Comment by yvaucher** [comment]
Starting to port stock_split_picking

**Comment by pedrobaeza** [comment]
Please take into account https://github.com/OCA/stock-logistics-workflow/pull/185

**Comment by yvaucher** [comment]
@pedrobaeza I'm on it already

**Comment by cyrilgdn** [comment]
Starting to work on picking_dispatch.

**Comment by pedrobaeza** [comment]
Please rename it to _stock_picking_dispatch_ to follow conventions.

**Comment by yajo** [comment]
stock_picking_show_returns by yourself #251 :wink:
