### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/stock-logistics-workflow#265]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] picking_dispatch_wave
- [ ] product_customer_code_picking
- [ ] product_serial
- [ ] stock_batch_picking
- [ ] stock_cancel
- [ ] stock_deposit
- [x] stock_disable_force_availability_button - By @rousseldenis - #338 
- [ ] stock_dropshipping_dual_invoice
- [x] ~~stock_filter_none_zero_qty~~ - Not needed since quants
- [ ] stock_inventory_retry_assign
- [ ] stock_location_flow_creator
- [ ] stock_move_backdating - By @tafaRU - #426 
- [ ] stock_move_description
- [ ] stock_move_on_hold
- [ ] stock_obsolete
- [ ] stock_ownership_availability_rules
- [x] stock_ownership_by_move - By @Cedric-Pigeon - #333 
- [x] stock_picking_back2draft - By @Saphery - #456 
- [ ] stock_picking_backorder_strategy - By @rousseldenis - #432 
- [ ] stock_picking_compute_delivery_date
- [ ] stock_picking_deliver_uos
- [x] stock_picking_invoice_link - By @eLBati - #347 
- [x] stock_picking_mass_action - By @cubells - #407 
- [ ] stock_picking_package_preparation - By @archetipo - #271 
- [ ] stock_picking_priority
- [ ] stock_picking_reorder_lines
- [x] stock_picking_show_return - By @pedrobaeza - #314 
- [x] stock_picking_show_backorder - By @aheficent - #362 
- [x] stock_picking_transfer_lot_autoassign - By @rgarnau - #366 
- [ ] stock_sale_filters
- [x] stock_split_picking - By @cubells - #310 
- [ ] stock_transfer_split_multi

**Comment by piqoni** [comment]
Hi there, 
Very new to this project (starting from today :) ). Tried to migrate `stock_batch_picking` module to 10 but when I try to install it, it complains when trying to import pooler.py (which is removed in https://github.com/odoo/odoo/commit/3019f4a48d465fc36e7edef4622e1317751fbff8) I saw that it is an old wrapper - do you have any suggestion/info/resource on how to substitute pooler.py?

**Comment by leorochael** [comment]
@piqoni, open a new PR with your attempt so we can comment on it, and mention it here, then we can add comments to your PR to help you along.

In the specific case you mention, I suggest just dropping [the lines from `PrintBatch.__init__()`](https://github.com/OCA/stock-logistics-workflow/blob/5f181a03299821e87c857b9b9fd1b919bde86f0c/stock_batch_picking/report/print_batch.py#L16):

        self.pool = pooler.get_pool(self.cr.dbname)
        self.cursor = self.cr
        self.uid = uid

And also drop the `time` key from the `self.localcontext.update({...})` call since the super class `report_sxw.rml_parse` already provides it.

And in the [only place that uses `self.pool` in `PrintBatch.set_context()`](https://github.com/OCA/stock-logistics-workflow/blob/5f181a03299821e87c857b9b9fd1b919bde86f0c/stock_batch_picking/report/print_batch.py#L34), replace the line:

        location_obj = self.pool.get('stock.location')

with something like:

        location_obj = self.localcontext['user'].env['stock.location']

And finally, replace the lines:

                key_dict = dict(
                    location_obj.name_get(
                        self.cursor, self.uid, [id1, id2]
                    )
                )

With something like:

                key_dict = dict(
                    location_obj.browse([id1, id2]).name_get()
                )

I'm not sure if that's enough to make this part of the code work and I suggest you study carefully the `report_sxw.rml_parse` class and how it's used in Odoo, but the above should take care of converting the uses of the old API inside the `PrintBatch` subclass.

**Comment by piqoni** [comment]
@leorochael Thank you. 

I started it here https://github.com/OCA/stock-logistics-workflow/pull/307

**Comment by fanha99** [comment]
hi, why the "stock_disable_force_availability_button" module is not in the list?

**Comment by pedrobaeza** [comment]
Because it wasn't present in the branch before creating the new version branch. But that's not a problem. You can migrate it the same although not in this list.

**Comment by bistaray** [comment]
Starting work on stock_move_backdating (to v10)

**Comment by usmanfarzandali** [comment]
@bistaray Thank you Sir...

**Comment by AaronHForgeFlow** [comment]
stock_picking_show_backorder: https://github.com/OCA/stock-logistics-workflow/pull/362

**Comment by eLBati** [comment]
Hi @bistaray any news about ```stock_move_backdating```?

**Comment by tafaRU** [comment]
I started to work on migration of `stock_move_backdating`.
Unfortunately I'm already stuck after having executed:
`git format-patch --keep-subject --stdout origin/10.0..origin/8.0 -- $MODULE | git am -3`.

Below you can see the error:

```
Applying: Update travis configuration
Using index info to reconstruct a base tree...
A	stock_move_backdating/__openerp__.py
error: patch non riuscita: stock_move_backdating/__init__.py:3
error: stock_move_backdating/__init__.py: la patch non può essere applicata
error: patch non riuscita: stock_move_backdating/stock.py:1
error: stock_move_backdating/stock.py: la patch non può essere applicata
error: patch non riuscita: stock_move_backdating/wizard/__init__.py:1
error: stock_move_backdating/wizard/__init__.py: la patch non può essere applicata
error: La tua patch è stata modificata manualmente?
Non può essere applicata ai blob registrati nel proprio index.
Patch failed at 0001 Update travis configuration
The copy of the patch that failed is found in: .git/rebase-apply/patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
```

It's raised: https://github.com/github/git-msysgit/blob/master/git-am.sh#L154

Any hints would be greatly appreciated!

**Comment by pedrobaeza** [comment]
This is because not a very good commit history (with pull/merges). You have to fix manually conflicts, and type `git add --all` and `git am --continue` several times until everything is fixed.

**Comment by tafaRU** [comment]
Thanks @pedrobaeza!
Fortunately I fixed by using https://stackoverflow.com/questions/13190679/error-while-applying-a-patch-in-git In other words by using `git am --keep-cr`.
See: https://github.com/tafaRU/stock-logistics-workflow/tree/10.0-mig-stock_move_backdating

**Comment by pedrobaeza** [comment]
Uhm, interesting. I didn't know about that option. I would check in other cases if this applies the same. It's not very frequent however that this happens.

**Comment by tafaRU** [comment]
Migration of `stock_move_backdating`: https://github.com/OCA/stock-logistics-workflow/pull/426

**Comment by Jortolsa-S73** [comment]
Migration of stock_cancel : #418
