### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/stock-logistics-workflow#377]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] picking_dispatch_wave
- [ ] product_customer_code_picking
- [x] product_expiry_simple - By @alan196 - #393 
- [ ] product_serial
- [ ] stock_auto_move
- [x] stock_batch_picking - By @carlosdauden - #437 
- [ ] stock_cancel
- [ ] stock_change_price_at_date
- [ ] stock_delivery_internal
- [ ] stock_disable_force_availability_button
- [x] ~~stock_dropshipping_dual_invoice~~ - Not needed since v9
- [ ] stock_inventory_retry_assign
- [ ] stock_location_flow_creator
- [x] stock_lot_scrap - By @cubells - #459 
- [ ] stock_move_backdating
- [ ] stock_move_description
- [ ] stock_move_on_hold
- [x] stock_no_negative - By @etobella - #389 
- [ ] stock_obsolete
- [ ] stock_ownership_availability_rules
- [ ] stock_ownership_by_move
- [x] stock_pack_operation_auto_fill - By @luistriana28 - #399 
- [x] stock_pack_operation_quick_lot > stock_move_quick_lot - By @sergio-teruel - #454 
- [x] stock_picking_back2draft - By @aheficent - #550 
- [x] stock_picking_backorder_strategy - By @mgosai - #482 
- [ ] stock_picking_compute_delivery_date
- [x] stock_picking_customer_ref - By @andreasdsp - #423 
- [ ] stock_picking_deliver_uos
- [x] stock_picking_filter_lot - By @lreficent - #467 
- [x] stock_picking_invoice_link - ~~By @Softdil - #409~~ By @chienandalu - #416 
- [x] ~~stock_picking_mass_assign - By @ougc27 - #390 replaced by stock_picking_mass_action~~
- [x] stock_picking_mass_action - By @mpanarin - #460 
- [x] stock_picking_operation_quick_change By @mreficent - #449 
- [x] stock_picking_package_preparation By @SimoRubi - #448 
- [x] stock_picking_package_preparation_line By @SimoRubi - #447 
- [ ] stock_picking_priority
- [ ] stock_picking_reorder_lines
- [x] stock_picking_sale_order_link - By @sergio-teruel - #455
- [x] stock_picking_send_by_mail - By @cubells - #452 
- [x] stock_picking_show_backorder - By @flotho - #398
- [x] stock_picking_show_return - By @flotho - #396 
- [x] ~~stock_picking_transfer_lot_autoassign - By @chienandalu - #430~~ Merged in stock_pack_operation_autofill in #435 
- [ ] stock_sale_filters
- [x] stock_split_picking - By @jcoux - #422 
- [ ] stock_transfer_split_multi

**Comment by lmgr0312** [comment]
Hello  

I'm going to migrate the module "stock_picking_transfer_lot_autoassign"

Regards

**Comment by pedrobaeza** [comment]
OK, noted.

**Comment by ougc27** [comment]
Hello

I'm migrating the module stock_picking_mass_assing to V11.

The PR is #390 

Regards!

**Comment by alan196** [comment]
Hello

I'm migrating the module product_expiry_simple to V11.

The PR is https://github.com/OCA/stock-logistics-workflow/pull/393

Regards

**Comment by fmdl** [comment]
stock picking show return : https://github.com/OCA/stock-logistics-workflow/pull/397
stock picking show backorder : https://github.com/OCA/stock-logistics-workflow/pull/398

**Comment by aitorbouzas** [comment]
stock_picking_invoice_link: #409

**Comment by SimoRubi** [comment]
Migrating stock_picking_package_preparation_line in https://github.com/OCA/stock-logistics-workflow/pull/447

**Comment by SimoRubi** [comment]
Migrating stock_picking_package_preparation in https://github.com/OCA/stock-logistics-workflow/pull/448

**Comment by aitorbouzas** [comment]
What happened to `stock_picking_back2draft`?

**Comment by pedrobaeza** [comment]
It was not present in branch 10.0 when this issue was automatically created. Any way, I don't consider it very useful, now that you can unlock pickings, cancel SO/PO and validate again, etc.

**Comment by emagdalenaC2i** [comment]
@pedrobaeza Please, check stock_pack_operation_quick_lot - By @sergio-teruel - #454 and this module is renamed as stock_move_quick_lot

stock_picking_mass_assign - By @ougc27 - #390 is closed and superseded by #460 (it is renamed as stock_picking_mass_action) and is already migrated and merged
Also check stock_picking_mass_action - By @mpanarin - #460

Please add to the list stock_picking_sale_order_link - By @sergio-teruel - #455 that is already migrated and merged

stock_picking_transfer_lot_autoassign - By @chienandalu - #430 is closed in favour of: #435 wich merges stock_picking_lot_autoassign into stock_pack_operation_autofill

**Comment by emagdalenaC2i** [comment]
@pedrobaeza the PR number in stock_picking_invoice_link - By @Softdil - #409 By @chienandalu - #415 should be #416 instead of 415

**Comment by rousseldenis** [comment]
> @pedrobaeza the PR number in stock_picking_invoice_link - By @Softdil - #409 By @chienandalu - #415 should be #416 instead of 415

Done

**Comment by emagdalenaC2i** [comment]
stock_picking_show_backorder - By @flotho - #397 is closed and superseed in #398 that is already merged

Please, change the PR number in stock_picking_show_return - By @flotho - #398 it should be #396

**Comment by bunhin** [comment]
Do not find "stock_picking_line_sequence" modul on migration list, please info whether it is not applicable for V11?.  I am trying to port from v10 or back from V12 to try solve issue i faced with stock delivery report where the printed line sequence of the report do not same as the sale order line. Thanks
